//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CategoryProducts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CategoryProducts.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string bg_BG {
            get {
                return ResourceManager.GetString("bg-BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Edit_profile {
            get {
                return ResourceManager.GetString("Edit profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input model.
        /// </summary>
        public static string Invalid_input_model {
            get {
                return ResourceManager.GetString("Invalid input model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text length should be in range [{0}-{1}].
        /// </summary>
        public static string InvalidTextLength {
            get {
                return ResourceManager.GetString("InvalidTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters [A-Z], [a-z], [0-9],[ - _ .].
        /// </summary>
        public static string InvalidUsernameCharacters {
            get {
                return ResourceManager.GetString("InvalidUsernameCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully change website language.
        /// </summary>
        public static string Successfully_change_website_language {
            get {
                return ResourceManager.GetString("Successfully change website language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully create an user account.
        /// </summary>
        public static string Successfully_create_an_user_account {
            get {
                return ResourceManager.GetString("Successfully create an user account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully login.
        /// </summary>
        public static string Successfully_login {
            get {
                return ResourceManager.GetString("Successfully login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully update user profile.
        /// </summary>
        public static string Successfully_update_user_profile {
            get {
                return ResourceManager.GetString("Successfully update user profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string User_does_not_exist {
            get {
                return ResourceManager.GetString("User does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist.
        /// </summary>
        public static string User_exist {
            get {
                return ResourceManager.GetString("User exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
